#!/usr/bin/env python
# -*- coding: UTF-8 -*-

DNS = """
# DNS config
# Generated by Nimbus
nameserver %(ns1)s
nameserver %(ns2)s
nameserver %(ns3)s
"""

INTERFACES = """
# Interfaces config
# Generated by Nimbus
auto lo
iface lo inet loopback
auto %(interface_name)s
"""

INTERFACES_DHCP = INTERFACES + "iface %(interface_name)s inet dhcp\n"

INTERFACES_STATIC = INTERFACES + \
"""
iface %(interface_name)s inet static
address %(interface_addr)s
netmask %(netmask)s
"""