#!/bin/bash
### BEGIN INIT INFO
# Provides:          nimbusclient
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO


PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME=nimbusclient
DESC="Nimbus Client Daemon"

# Identify the system.
SYSTEM_OS=linux
DAEMON=/usr/bin/nimbusclientservice
STOPDAEMON="$DAEMON stop"
STARTDAEMON="$DAEMON start"


if [ ! -f $DAEMON ];
then 
	echo 'ERR: The daemon file is no present.'; 
	exit 0;
fi;

set -e

case "$1" in
  start)
	echo -n "Starting $DESC: "
	$STARTDAEMON
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	$STOPDAEMON
	echo "$NAME."
	;;
  #reload)
	#
	#	If the daemon can reload its config files on the fly
	#	for example by sending it SIGHUP, do it here.
	#
	#	If the daemon responds to changes in its config file
	#	directly anyway, make this a do-nothing entry.
	#
	# echo "Reloading $DESC configuration files."
	# start-stop-daemon --stop --signal 1 --quiet --pidfile \
	#	/var/run/$NAME.pid --exec $DAEMON
  #;;
  restart|force-reload)
	#
	#	If the "reload" option is implemented, move the "force-reload"
	#	option to the "reload" entry above. If not, "force-reload" is
	#	just the same as "restart".
	#
	echo -n "Restarting $DESC: "
	$STOPDAEMON > /dev/null || echo;
	sleep 1;
	$STARTDAEMON;
	echo "$NAME.";
	;;
  *)
	N=/etc/init.d/$NAME
	# echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
